### ISSUE TITLE
Order of sequences within contig files

### ISSUE THREAD

**Issue by KalinNonchev** [IndexThePlanet/Logan#11]
Dear Logan Team,

Thank you for providing this valuable resource. Could you please provide more information about the order of the sequences within a contig file? Are there any assumptions about whether they are ordered/sorted?

Thank you in advance for your assistance!

Best,

**Comment by rchikhi** [comment]
They aren't sorted, but output by the assembler as it explores the graph, so, no particular order but probably a bias towards longer sequences.
