### ISSUE TITLE
Metadata of contig , like N50.

### ISSUE THREAD

**Issue by lkalbert001** [IndexThePlanet/Logan#12]
Thank you for your selfless contributions. The Logan project helps me identify introns in DNA sequences. I have a question: some contig sequences are noticeably short, such as ERR11179910.contigs.fa. Could you provide the N50 of the contig file or other assembly quality-related information for higher-quality contig data selection? Thanks.

**Comment by rchikhi** [comment]
hi, yes, good idea, added here:
https://github.com/IndexThePlanet/Logan/blob/main/Stats-v1.md#detailed-statistics
