### ISSUE TITLE
"--no-sign-request"  flag is missing here

### ISSUE THREAD

**Issue by CamilaDuitama** [IndexThePlanet/Logan#2]
https://github.com/IndexThePlanet/Logan/blob/22014aa8e0f237e39fd7f1da0c1980476c16794e/Accessions.md?plain=1#L25C1-L26C1

Should be

```
cat accessions.txt | xargs -I{} aws s3 cp s3://logan-pub/u/{}/{}.unitigs.fa.zst . ----no-sign-request
```

**Comment by rchikhi** [comment]
ahhhh thanks! I was worried that flag was missing everywhere but it was just in some pages like this one. Fixed it.

In principle you don't need this `--no-sign-request` flag if your aws command-line client is configured with an account (which anyway won't get charged).
