### ISSUE TITLE
Create Documentation on Logan Contig/Unitig headers meta-data

### ISSUE THREAD

**Issue by ababaian** [IndexThePlanet/Logan#4]
There's a contig page for accessing the data, but there isn't a description of how the data was created and/or what meta-data is in the header of each fasta file. A description of this will ensure people on-boarding can make full use of the data from the get go (i.e. they know the assembly graph exists)

**Comment by rchikhi** [comment]
yeah I realize that contigs doc needs to be improved (for the looping issue as well)
Headers were described in https://github.com/IndexThePlanet/Logan/blob/main/Unitigs.md#data-format and they apply to contigs as well

**Comment by rchikhi** [comment]
added to Contigs page
