### ISSUE TITLE
Is minimum abundance filter used in Cuttlefish2/Minia?

### ISSUE THREAD

**Issue by mr-eyes** [IndexThePlanet/Logan#9]
Hey Rayan,

I was exploring some compressed logan runs and noticed a significant loss of k-mers when comparing unitigs/contigs to the full read content in the SRA. Are you applying a filter to exclude k-mers with low abundance (e.g., 1 or 2), as they're likely errors? Or maybe I am getting something wrong about how Logan works.

Thanks!

**Comment by mr-eyes** [comment]
I think it was a dumb question, it totally make sense to trim errors. I will appreciate if you can post the abundance cutoff used. Thanks!

**Comment by rchikhi** [comment]
hi, yes, k-mers seen only once are discarded

**Comment by mr-eyes** [comment]
thx!
